"use client";

import React, { useState, useEffect } from "react";
import {
  Play, BarChart3, TrendingUp, Users, 
  Clock, Plus, ArrowUpRight, Search, Filter,
  FileText, Sparkles, Settings, Share2, MoreHorizontal,
  Video, CheckCircle2, AlertCircle, X, ChevronRight, 
  Copy, Check, Info, RefreshCw, Send
} from "lucide-react";

// Mock video analytics stats
const mockStats = [
  { label: "Total Views", value: "1.25M", change: "+12.5%", icon: Play, color: "text-red-500" },
  { label: "Watch Time (h)", value: "45.2K", change: "+8.2%", icon: Clock, color: "text-primary" },
  { label: "Subscribers", value: "82.4K", change: "+5.1%", icon: Users, color: "text-accent" },
  { label: "Avg. Retention", value: "68%", change: "+2.4%", icon: TrendingUp, color: "text-success" },
];

const initialVideos = [
  { id: "v1", title: "How to Scale your CRM with AI", views: "125K", engagement: "92%", status: "Live", thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=60" },
  { id: "v2", title: "Automating Lead Gen: A Complete Guide", views: "82K", engagement: "88%", status: "Live", thumbnail: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=200&auto=format&fit=crop&q=60" },
  { id: "v3", title: "Next-Gen Marketing Trends 2026", views: "45K", engagement: "95%", status: "Processing", thumbnail: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=200&auto=format&fit=crop&q=60" },
];

// Pre-seeded production queue scripts
const initialProductions = [
  {
    id: "p1",
    topic: "AI Agent Workforce Integration",
    targetAudience: "SaaS Founders",
    tone: "Professional & Energetic",
    status: "completed",
    suggestedTitles: [
      "We Hired 5 AI Agents to Run Our SaaS (Full Strategy) 🤖",
      "How to Build a Multi-Agent AI Team in 2026",
      "Why You're Doing AI Operations WRONG (And How to Fix It)"
    ],
    suggestedTags: ["ai agents", "saas growth", "business automation", "crm strategy"],
    estimatedDuration: "8-10 minutes",
    thumbnailConcept: "A futuristic glowing office with virtual holographic robot agents collaborating around a table, bold yellow caption: '0 MANPOWER'",
    createdAt: "1 hour ago",
    script: {
      hook: "[Visual Cue: Cut to host smiling in front of a giant holographic network diagram.] Host: What if I told you that the secret to scaling your SaaS from $10k to $100k MRR isn't hiring more engineers or sales reps, but instantiating a custom team of autonomous AI agents? Today, I'm showing you the exact framework to make it happen.",
      intro: "[Visual Cue: Host walks over to a whiteboard, tapping it to reveal key steps.] Host: In this guide, we are looking at the exact roles you need: Chief AI Ops controllers, Trend research scouts, and Creative copywriters. By the end, you'll be ready to run these agents yourself.",
      bodyPoints: [
        {
          title: "1. Orchestration via CAIO",
          content: "[Visual Cue: Screen recording of a visual workflow graph executing in real-time.] Host: Think of the Chief AI Ops as your master controller. It deconstructs your goals into small tasks and delegates them to specialized agents, tracking health and performance metrics seamlessly."
        },
        {
          title: "2. The Copywriter Agent Loop",
          content: "[Visual Cue: Close-up of a WhatsApp message draft being generated by AI, showing high-intent variables.] Host: Once a trend is located, our copywriter structures the campaign copy. It is personalized and verified. Full outbound operations, fully automated."
        }
      ],
      cta: "[Visual Cue: Glowing QR code overlay on screen.] Host: Click the link below to get our pre-built Multi-Agent workforce templates and 1,000 free execution tasks. Don't forget to hit subscribe!",
      outro: "[Visual Cue: Cut to standard out-ro logo card with smooth neon lighting.] Host: Stay agentic, work less, and let OMNI-SIGMA 360 build the future for you. Bye!"
    }
  }
];

export default function VideoContent() {
  const [activeTab, setActiveSection] = useState<'analytics' | 'production'>('analytics');
  const [isChannelConnected, setIsChannelConnected] = useState(false);
  const [isConnecting, setIsConnecting] = useState(false);
  const [showConnectModal, setShowConnectModal] = useState(false);
  const [showProductionModal, setShowProductionModal] = useState(false);
  
  // Production Wizard Form State
  const [topic, setTopic] = useState("");
  const [audience, setAudience] = useState("");
  const [tone, setTone] = useState("Professional & Energetic");
  
  // Production Execution State
  const [isProducing, setIsProducing] = useState(false);
  const [productionStep, setProductionStep] = useState(0);
  const [productions, setProductions] = useState(initialProductions);
  const [selectedProduction, setSelectedProduction] = useState<any>(initialProductions[0]);
  
  // UI Helpers
  const [copiedTag, setCopiedTag] = useState<string | null>(null);
  const [isScriptCopied, setIsScriptCopied] = useState(false);
  const [isPublished, setIsPublished] = useState(false);

  // Trigger simulated channel connection
  const handleConnectChannel = () => {
    setIsConnecting(true);
    setTimeout(() => {
      setIsConnecting(false);
      setIsChannelConnected(true);
      setShowConnectModal(false);
    }, 2000);
  };

  // Run AI Video Script Production Simulation
  const handleStartProduction = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topic || !audience) return;
    
    setIsProducing(true);
    setProductionStep(1); // Scout Agent
    
    // Step 1 Simulation
    setTimeout(() => {
      setProductionStep(2); // Copywriter Agent
      
      // Step 2 Simulation
      setTimeout(() => {
        setProductionStep(3); // QC Agent
        
        // Finalize API call and insert
        setTimeout(async () => {
          try {
            const res = await fetch("/api/video", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ topic, targetAudience: audience, tone }),
            });
            const result = await res.json();
            
            if (result.success && result.data) {
              const newProd = {
                id: `p_${Date.now()}`,
                topic: result.data.topic,
                targetAudience: result.data.targetAudience,
                tone: result.data.tone,
                status: "completed",
                suggestedTitles: result.data.suggestedTitles,
                suggestedTags: result.data.suggestedTags,
                estimatedDuration: result.data.estimatedDuration,
                thumbnailConcept: result.data.thumbnailConcept,
                createdAt: "Just now",
                script: result.data.script
              };
              
              setProductions([newProd, ...productions]);
              setSelectedProduction(newProd);
            }
          } catch (err) {
            console.error("Failed to generate AI script:", err);
          } finally {
            setIsProducing(false);
            setProductionStep(0);
            setShowProductionModal(false);
            setTopic("");
            setAudience("");
          }
        }, 1500);
      }, 1500);
    }, 1500);
  };

  // Copy whole script helper
  const handleCopyScript = () => {
    if (!selectedProduction) return;
    const scriptText = `
TITLE OPTIONS:
${selectedProduction.suggestedTitles.map((t: string, i: number) => `${i + 1}. ${t}`).join("\n")}

ESTIMATED DURATION: ${selectedProduction.estimatedDuration}
RECOMMENDED THUMBNAIL: ${selectedProduction.thumbnailConcept}

--- SCRIPT START ---
HOOK:
${selectedProduction.script.hook}

INTRO:
${selectedProduction.script.intro}

MAIN POINTS:
${selectedProduction.script.bodyPoints.map((bp: any) => `${bp.title}:\n${bp.content}`).join("\n\n")}

CALL TO ACTION:
${selectedProduction.script.cta}

OUTRO:
${selectedProduction.script.outro}
--- SCRIPT END ---
    `.trim();

    navigator.clipboard.writeText(scriptText);
    setIsScriptCopied(true);
    setTimeout(() => setIsScriptCopied(false), 2000);
  };

  const handleCopyTag = (tag: string) => {
    navigator.clipboard.writeText(tag);
    setCopiedTag(tag);
    setTimeout(() => setCopiedTag(null), 1500);
  };

  return (
    <div className="space-y-6 stagger-children">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
            Video <span className="gradient-text">Studio</span> 🎬
          </h1>
          <p className="text-sm text-muted-foreground mt-1">Manage your YouTube channel strategy and AI-driven video content operations.</p>
        </div>
        <div className="flex items-center gap-3">
          {isChannelConnected ? (
            <div className="glass-card px-4 py-2 flex items-center gap-2 border-emerald-500/20 bg-emerald-500/5 text-xs text-emerald-400 font-semibold rounded-xl">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
              Connected: OMNI Tech
            </div>
          ) : (
            <button 
              onClick={() => setShowConnectModal(true)}
              className="glass-button px-4 py-2 text-xs font-semibold flex items-center gap-2 hover:border-primary/50 hover:bg-primary/5 transition-all"
            >
              <Share2 className="w-4 h-4 text-primary" />
              Connect Channel
            </button>
          )}
          <button 
            onClick={() => setShowProductionModal(true)}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-primary to-accent text-white font-semibold text-sm hover:opacity-90 hover:shadow-lg hover:shadow-primary/20 active:scale-95 transition-all"
          >
            <Plus className="w-4 h-4" /> New Production
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 p-1 bg-surface/50 border border-border rounded-xl w-fit">
        <button 
          onClick={() => setActiveSection('analytics')}
          className={`px-4 py-2 text-xs font-medium rounded-lg transition-all ${activeTab === 'analytics' ? 'bg-primary text-white shadow-lg shadow-primary/20' : 'text-muted-foreground hover:text-foreground'}`}
        >
          Channel Analytics
        </button>
        <button 
          onClick={() => setActiveSection('production')}
          className={`px-4 py-2 text-xs font-medium rounded-lg transition-all ${activeTab === 'production' ? 'bg-primary text-white shadow-lg shadow-primary/20' : 'text-muted-foreground hover:text-foreground'}`}
        >
          Production Queue ({productions.length})
        </button>
      </div>

      {activeTab === 'analytics' ? (
        <>
          {/* Stats Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {mockStats.map((stat, i) => {
              const Icon = stat.icon;
              return (
                <div key={i} className="glass-card p-5 group hover:border-primary/30 transition-all duration-300 relative overflow-hidden">
                  <div className="flex items-center justify-between mb-3 relative z-10">
                    <div className="p-2 rounded-lg bg-surface/80 border border-border group-hover:border-primary/20 transition-colors">
                      <Icon className={`w-5 h-5 ${stat.color}`} />
                    </div>
                    <span className="text-[10px] font-bold text-success bg-success/10 px-2 py-0.5 rounded-full">{isChannelConnected ? stat.change : "+0.0%"}</span>
                  </div>
                  <p className="text-2xl font-bold relative z-10">{isChannelConnected ? stat.value : "---"}</p>
                  <p className="text-xs text-muted-foreground mt-1 relative z-10">{stat.label}</p>
                  <div className="absolute -right-4 -bottom-4 w-16 h-16 rounded-full bg-primary/5 blur-xl group-hover:opacity-100 transition-opacity opacity-0" />
                </div>
              );
            })}
          </div>

          {/* Main Analytics Area */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 glass-card p-6 flex flex-col justify-between">
              <div className="flex items-center justify-between mb-6">
                <div>
                  <h3 className="font-semibold text-sm">Performance Overview</h3>
                  <p className="text-[10px] text-muted-foreground mt-0.5">Views and average engagement rate over the past 30 days.</p>
                </div>
                <div className="flex gap-2">
                  <span className="px-2.5 py-1 bg-surface border border-border text-[10px] font-medium text-muted-foreground rounded-lg">Last 30 Days</span>
                </div>
              </div>
              {isChannelConnected ? (
                <div className="h-64 w-full relative flex items-end">
                  {/* Premium interactive SVG Area Chart */}
                  <svg className="w-full h-full" viewBox="0 0 500 200" preserveAspectRatio="none">
                    <defs>
                      <linearGradient id="viewsGrad" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="var(--color-primary, #6366f1)" stopOpacity="0.4"/>
                        <stop offset="100%" stopColor="var(--color-primary, #6366f1)" stopOpacity="0.0"/>
                      </linearGradient>
                    </defs>
                    {/* Grid Lines */}
                    <line x1="0" y1="50" x2="500" y2="50" stroke="#1f2937" strokeWidth="0.5" strokeDasharray="5,5" />
                    <line x1="0" y1="100" x2="500" y2="100" stroke="#1f2937" strokeWidth="0.5" strokeDasharray="5,5" />
                    <line x1="0" y1="150" x2="500" y2="150" stroke="#1f2937" strokeWidth="0.5" strokeDasharray="5,5" />
                    
                    {/* Area path */}
                    <path 
                      d="M 0 180 Q 80 150 120 120 T 250 80 T 380 40 T 500 20 L 500 200 L 0 200 Z" 
                      fill="url(#viewsGrad)" 
                    />
                    
                    {/* Line path */}
                    <path 
                      d="M 0 180 Q 80 150 120 120 T 250 80 T 380 40 T 500 20" 
                      fill="none" 
                      stroke="var(--color-primary, #6366f1)" 
                      strokeWidth="3" 
                    />
                  </svg>
                  {/* Overlay labels */}
                  <div className="absolute top-2 left-2 text-[10px] bg-primary/10 border border-primary/20 text-primary px-2 py-0.5 rounded-md font-semibold">125K Peak Views</div>
                </div>
              ) : (
                <div className="h-64 flex flex-col items-center justify-center border border-dashed border-border rounded-xl bg-surface/30 text-center p-6">
                  <Share2 className="w-8 h-8 text-muted-foreground opacity-30 mb-3 animate-pulse" />
                  <p className="text-xs font-semibold text-muted-foreground">Channel Not Connected</p>
                  <p className="text-[10px] text-muted-foreground/60 max-w-xs mt-1">Connect your YouTube channel in the top right to populate real-time growth analytics and engagement graphs.</p>
                </div>
              )}
            </div>

            <div className="glass-card p-6">
              <h3 className="font-semibold text-sm mb-4">Top Performing Videos</h3>
              <div className="space-y-4">
                {initialVideos.map((video) => (
                  <div key={video.id} className="flex items-center gap-3 group cursor-pointer hover:bg-surface-hover/30 p-1.5 rounded-lg transition-colors">
                    <div className="w-16 h-10 rounded-lg overflow-hidden border border-border group-hover:border-primary/30 transition-all shrink-0 relative bg-muted">
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img src={video.thumbnail} alt={video.title} className="w-full h-full object-cover" />
                      <div className="absolute inset-0 bg-black/35 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                        <Play className="w-3.5 h-3.5 text-white fill-white" />
                      </div>
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-xs font-semibold truncate group-hover:text-primary transition-colors">{video.title}</p>
                      <p className="text-[10px] text-muted-foreground mt-0.5">{isChannelConnected ? `${video.views} views` : "---"} · {isChannelConnected ? `${video.engagement} engagement` : "---"}</p>
                    </div>
                    <ArrowUpRight className="w-3.5 h-3.5 text-muted-foreground opacity-0 group-hover:opacity-100 transition-all shrink-0" />
                  </div>
                ))}
              </div>
              <button 
                onClick={() => {
                  if (!isChannelConnected) setShowConnectModal(true);
                  else setActiveSection('production');
                }}
                className="w-full mt-6 py-2.5 text-[11px] font-semibold border border-border rounded-xl hover:bg-surface-hover/60 active:scale-[0.98] transition-all"
              >
                {isChannelConnected ? "View Strategy Pipeline" : "Connect to View Performance"}
              </button>
            </div>
          </div>
        </>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 h-[calc(100vh-230px)] items-stretch">
          {/* Left panel: Queue items */}
          <div className="glass-card flex flex-col overflow-hidden h-full">
            <div className="p-4 border-b border-border flex items-center justify-between">
              <h2 className="text-xs font-bold uppercase tracking-widest text-muted-foreground">AI Strategy Queue ({productions.length})</h2>
              <button 
                onClick={() => setShowProductionModal(true)} 
                className="p-1 rounded-lg border border-border hover:bg-surface-hover text-muted-foreground hover:text-foreground transition-all"
              >
                <Plus className="w-4 h-4" />
              </button>
            </div>
            {productions.length === 0 ? (
              <div className="flex-1 flex flex-col items-center justify-center p-8 text-center space-y-4">
                <div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center">
                  <Sparkles className="w-8 h-8 text-primary" />
                </div>
                <div>
                  <h3 className="font-bold text-sm">Production Queue Empty</h3>
                  <p className="text-xs text-muted-foreground mt-1 max-w-xs mx-auto">Start a new production task to have the Video Director generate scripts and metadata.</p>
                </div>
                <button 
                  onClick={() => setShowProductionModal(true)}
                  className="px-5 py-2 rounded-xl bg-primary text-white text-xs font-bold hover:bg-primary-hover transition-all"
                >
                  Launch AI Director
                </button>
              </div>
            ) : (
              <div className="flex-1 overflow-y-auto divide-y divide-border-subtle">
                {productions.map((prod) => (
                  <button
                    key={prod.id}
                    onClick={() => {
                      setSelectedProduction(prod);
                      setIsPublished(false);
                    }}
                    className={`w-full p-4 text-left hover:bg-surface-hover/30 transition-all flex gap-3 items-start ${selectedProduction?.id === prod.id ? 'bg-primary/5 border-l-2 border-primary' : ''}`}
                  >
                    <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0 text-primary">
                      <Video className="w-4 h-4" />
                    </div>
                    <div className="min-w-0 flex-1">
                      <p className="text-xs font-bold truncate text-foreground">{prod.topic}</p>
                      <p className="text-[10px] text-muted-foreground truncate mt-0.5">Audience: {prod.targetAudience}</p>
                      <div className="flex items-center gap-2 mt-1.5">
                        <span className="text-[9px] font-semibold bg-success/15 text-success px-1.5 py-0.5 rounded-md uppercase tracking-wide">
                          {prod.status}
                        </span>
                        <span className="text-[10px] text-muted-foreground">{prod.createdAt}</span>
                      </div>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Right panel: Details Visualizer */}
          <div className="lg:col-span-2 glass-card flex flex-col overflow-hidden h-full">
            {selectedProduction ? (
              <>
                {/* Visualizer Header */}
                <div className="p-4 border-b border-border flex items-center justify-between bg-surface/30 backdrop-blur-sm sticky top-0 z-10 shrink-0">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center">
                      <Sparkles className="w-4 h-4 text-primary animate-pulse" />
                    </div>
                    <div>
                      <h3 className="text-xs font-bold text-foreground">AI Outline: {selectedProduction.topic}</h3>
                      <p className="text-[10px] text-muted-foreground mt-0.5">Audience: {selectedProduction.targetAudience} · Tone: {selectedProduction.tone}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <button 
                      onClick={handleCopyScript}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-surface border border-border text-xs font-semibold rounded-lg hover:bg-surface-hover active:scale-95 transition-all"
                    >
                      {isScriptCopied ? (
                        <>
                          <Check className="w-3.5 h-3.5 text-success" />
                          <span className="text-success">Copied!</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5 text-muted-foreground" />
                          <span>Copy Script</span>
                        </>
                      )}
                    </button>
                    <button 
                      onClick={() => setIsPublished(true)}
                      disabled={isPublished}
                      className="flex items-center gap-1.5 px-3.5 py-1.5 bg-primary text-white text-xs font-bold rounded-lg hover:bg-primary-hover active:scale-95 transition-all disabled:bg-success disabled:opacity-90"
                    >
                      {isPublished ? (
                        <>
                          <CheckCircle2 className="w-3.5 h-3.5" />
                          <span>Published to Workflow</span>
                        </>
                      ) : (
                        <>
                          <Send className="w-3.5 h-3.5" />
                          <span>Publish to Operations</span>
                        </>
                      )}
                    </button>
                  </div>
                </div>

                {/* Visualizer Grid Content */}
                <div className="flex-1 overflow-hidden flex flex-col md:flex-row divide-y md:divide-y-0 md:divide-x divide-border">
                  {/* Script Text */}
                  <div className="flex-1 overflow-y-auto p-5 space-y-5">
                    {/* Hook Section */}
                    <div className="space-y-1.5">
                      <span className="text-[9px] font-bold uppercase tracking-wider text-primary bg-primary/10 px-2 py-0.5 rounded-full">Hook (First 30s)</span>
                      <div className="p-4 bg-surface/40 border border-border rounded-xl text-xs leading-relaxed text-foreground/90 italic shadow-sm relative overflow-hidden">
                        {/* Highlight visual cue */}
                        {selectedProduction.script.hook.split(/(\[Visual Cue:[^\]]+\])/g).map((chunk: string, idx: number) => {
                          if (chunk.startsWith("[Visual Cue:")) {
                            return <strong key={idx} className="text-accent not-italic font-bold block mb-2">{chunk}</strong>;
                          }
                          return <span key={idx}>{chunk}</span>;
                        })}
                      </div>
                    </div>

                    {/* Intro Section */}
                    <div className="space-y-1.5">
                      <span className="text-[9px] font-bold uppercase tracking-wider text-accent bg-accent/10 px-2 py-0.5 rounded-full">Intro</span>
                      <div className="p-4 bg-surface/40 border border-border rounded-xl text-xs leading-relaxed text-foreground/90 italic shadow-sm">
                        {selectedProduction.script.intro.split(/(\[Visual Cue:[^\]]+\])/g).map((chunk: string, idx: number) => {
                          if (chunk.startsWith("[Visual Cue:")) {
                            return <strong key={idx} className="text-accent not-italic font-bold block mb-2">{chunk}</strong>;
                          }
                          return <span key={idx}>{chunk}</span>;
                        })}
                      </div>
                    </div>

                    {/* Body Points */}
                    {selectedProduction.script.bodyPoints.map((point: any, index: number) => (
                      <div key={index} className="space-y-1.5">
                        <span className="text-[9px] font-bold uppercase tracking-wider text-success bg-success/10 px-2 py-0.5 rounded-full">Point {index + 1}: {point.title}</span>
                        <div className="p-4 bg-surface/40 border border-border rounded-xl text-xs leading-relaxed text-foreground/90 italic shadow-sm">
                          {point.content.split(/(\[Visual Cue:[^\]]+\])/g).map((chunk: string, idx: number) => {
                            if (chunk.startsWith("[Visual Cue:")) {
                              return <strong key={idx} className="text-accent not-italic font-bold block mb-2">{chunk}</strong>;
                            }
                            return <span key={idx}>{chunk}</span>;
                          })}
                        </div>
                      </div>
                    ))}

                    {/* CTA & Outro */}
                    <div className="space-y-1.5">
                      <span className="text-[9px] font-bold uppercase tracking-wider text-warning bg-warning/10 px-2 py-0.5 rounded-full">Call to Action (CTA)</span>
                      <div className="p-4 bg-surface/40 border border-border rounded-xl text-xs leading-relaxed text-foreground/90 italic shadow-sm">
                        {selectedProduction.script.cta.split(/(\[Visual Cue:[^\]]+\])/g).map((chunk: string, idx: number) => {
                          if (chunk.startsWith("[Visual Cue:")) {
                            return <strong key={idx} className="text-accent not-italic font-bold block mb-2">{chunk}</strong>;
                          }
                          return <span key={idx}>{chunk}</span>;
                        })}
                      </div>
                    </div>

                    <div className="space-y-1.5">
                      <span className="text-[9px] font-bold uppercase tracking-wider text-muted-foreground bg-muted px-2 py-0.5 rounded-full">Outro</span>
                      <div className="p-4 bg-surface/40 border border-border rounded-xl text-xs leading-relaxed text-foreground/90 italic shadow-sm">
                        {selectedProduction.script.outro.split(/(\[Visual Cue:[^\]]+\])/g).map((chunk: string, idx: number) => {
                          if (chunk.startsWith("[Visual Cue:")) {
                            return <strong key={idx} className="text-accent not-italic font-bold block mb-2">{chunk}</strong>;
                          }
                          return <span key={idx}>{chunk}</span>;
                        })}
                      </div>
                    </div>
                  </div>

                  {/* Metadata Sidebar */}
                  <div className="w-full md:w-64 shrink-0 overflow-y-auto p-5 bg-surface/20 space-y-6">
                    {/* Suggested Titles */}
                    <div className="space-y-2">
                      <h4 className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                        <TrendingUp className="w-3.5 h-3.5 text-primary" /> Title Concepts
                      </h4>
                      <div className="space-y-2">
                        {selectedProduction.suggestedTitles.map((title: string, i: number) => (
                          <div key={i} className="p-2.5 bg-surface/60 border border-border rounded-lg text-[11px] font-semibold text-foreground leading-normal shadow-sm">
                            {title}
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* SEO Tags */}
                    <div className="space-y-2">
                      <h4 className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                        <Search className="w-3.5 h-3.5 text-accent" /> Recommended Tags
                      </h4>
                      <div className="flex flex-wrap gap-1.5">
                        {selectedProduction.suggestedTags.map((tag: string, i: number) => (
                          <button 
                            key={i} 
                            onClick={() => handleCopyTag(tag)}
                            className="px-2.5 py-1 bg-surface border border-border-subtle hover:border-accent/40 rounded-lg text-[10px] font-semibold flex items-center gap-1 transition-all text-muted-foreground hover:text-foreground"
                          >
                            #{tag}
                            {copiedTag === tag ? <Check className="w-3 h-3 text-success shrink-0" /> : <Copy className="w-2.5 h-2.5 opacity-55 shrink-0" />}
                          </button>
                        ))}
                      </div>
                    </div>

                    {/* Estimated Duration */}
                    <div className="space-y-2">
                      <h4 className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                        <Clock className="w-3.5 h-3.5 text-success" /> Production Info
                      </h4>
                      <div className="p-3 bg-surface/60 border border-border rounded-lg text-xs font-semibold text-muted-foreground space-y-1.5">
                        <div className="flex justify-between"><span>Duration:</span> <span className="text-foreground">{selectedProduction.estimatedDuration}</span></div>
                        <div className="flex justify-between"><span>Target:</span> <span className="text-foreground truncate max-w-[120px]">{selectedProduction.targetAudience}</span></div>
                        <div className="flex justify-between"><span>Tone:</span> <span className="text-foreground">{selectedProduction.tone}</span></div>
                      </div>
                    </div>

                    {/* Thumbnail Concept */}
                    <div className="space-y-2">
                      <h4 className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                        <Info className="w-3.5 h-3.5 text-warning" /> Thumbnail Guide
                      </h4>
                      <div className="p-3 bg-warning/5 border border-warning/15 rounded-lg text-[11px] text-muted-foreground leading-relaxed italic">
                        &ldquo;{selectedProduction.thumbnailConcept}&rdquo;
                      </div>
                    </div>
                  </div>
                </div>
              </>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-muted-foreground p-12 text-center">
                <div className="w-16 h-16 rounded-full bg-muted/30 flex items-center justify-center mb-4">
                  <Play className="w-8 h-8 opacity-20" />
                </div>
                <p className="text-sm font-semibold text-foreground">Select a strategy outline from the queue</p>
                <p className="text-xs text-muted-foreground mt-1">Or launch the AI director to start a fresh production workflow.</p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Connect Channel Modal */}
      {showConnectModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setShowConnectModal(false)} />
          <div className="relative w-full max-w-md glass-card overflow-hidden p-6 space-y-6" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between border-b border-border pb-3">
              <h3 className="font-bold text-base flex items-center gap-2">Connect YouTube Channel</h3>
              <button onClick={() => setShowConnectModal(false)} className="p-1.5 rounded-lg hover:bg-surface-hover text-muted-foreground hover:text-foreground"><X className="w-4 h-4" /></button>
            </div>
            
            {isConnecting ? (
              <div className="py-8 text-center space-y-4">
                <div className="relative w-16 h-16 mx-auto flex items-center justify-center">
                  <div className="absolute inset-0 rounded-full border-4 border-primary/20 border-t-primary animate-spin" />
                  <Video className="w-6 h-6 text-primary animate-pulse" />
                </div>
                <div>
                  <p className="text-xs font-bold">Authorizing OMNI strategy director...</p>
                  <p className="text-[10px] text-muted-foreground mt-1">Requesting OAuth channel metadata and views permission.</p>
                </div>
              </div>
            ) : (
              <div className="space-y-4">
                <p className="text-xs text-muted-foreground leading-relaxed">
                  Connect your brand&apos;s YouTube channel to allow OMNI-SIGMA 360&apos;s Chief AI Ops to fetch views, retention benchmarks, and execute direct publishes.
                </p>
                <div className="p-3 bg-surface/50 border border-border rounded-xl text-[10px] text-muted-foreground flex items-start gap-2 leading-relaxed">
                  <Info className="w-4 h-4 text-primary shrink-0" />
                  <span>We only request read permissions for analytics and read/write for channel strategies. Your credentials are fully encrypted.</span>
                </div>
                <div className="flex justify-end gap-3 pt-3 border-t border-border">
                  <button onClick={() => setShowConnectModal(false)} className="px-4 py-2 border border-border text-xs font-semibold rounded-lg hover:bg-surface-hover transition-colors">Cancel</button>
                  <button onClick={handleConnectChannel} className="px-5 py-2 bg-primary text-white text-xs font-bold rounded-lg hover:bg-primary-hover active:scale-[0.98] transition-all">Authorize OMNI Channel</button>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* New Production Wizard Modal */}
      {showProductionModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => !isProducing && setShowProductionModal(false)} />
          <div className="relative w-full max-w-lg glass-card overflow-hidden p-6" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between border-b border-border pb-3 mb-5">
              <h3 className="font-bold text-base flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-primary animate-pulse" /> Launch AI Video Director
              </h3>
              <button 
                onClick={() => setShowProductionModal(false)} 
                disabled={isProducing}
                className="p-1.5 rounded-lg hover:bg-surface-hover text-muted-foreground hover:text-foreground disabled:opacity-50"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
            
            {isProducing ? (
              <div className="py-10 text-center space-y-6">
                <div className="relative w-20 h-20 mx-auto flex items-center justify-center">
                  <div className="absolute inset-0 rounded-full border-4 border-primary/10 border-t-primary animate-spin" style={{ animationDuration: '1.2s' }} />
                  <Video className="w-8 h-8 text-primary animate-pulse" />
                </div>
                
                <div className="max-w-xs mx-auto space-y-2">
                  <p className="text-sm font-bold">Generative Scripting In Progress...</p>
                  
                  {/* Step Logs */}
                  <div className="space-y-1.5 pt-2">
                    <div className="flex items-center gap-2 text-left bg-surface/50 p-2 border border-border rounded-lg text-[11px]">
                      {productionStep >= 1 ? (
                        <CheckCircle2 className="w-4 h-4 text-success shrink-0" />
                      ) : (
                        <RefreshCw className="w-3.5 h-3.5 text-muted-foreground shrink-0 animate-spin" />
                      )}
                      <span className={`${productionStep >= 1 ? 'text-foreground font-semibold' : 'text-muted-foreground'}`}>
                        Trend Scout: Auditing CTR opportunities...
                      </span>
                    </div>

                    <div className="flex items-center gap-2 text-left bg-surface/50 p-2 border border-border rounded-lg text-[11px]">
                      {productionStep >= 2 ? (
                        <CheckCircle2 className="w-4 h-4 text-success shrink-0" />
                      ) : productionStep === 1 ? (
                        <RefreshCw className="w-3.5 h-3.5 text-muted-foreground shrink-0 animate-spin" />
                      ) : (
                        <div className="w-3.5 h-3.5 border border-border rounded-full shrink-0" />
                      )}
                      <span className={`${productionStep >= 2 ? 'text-foreground font-semibold' : 'text-muted-foreground'}`}>
                        Copywriter Agent: Generating hook & visual cues...
                      </span>
                    </div>

                    <div className="flex items-center gap-2 text-left bg-surface/50 p-2 border border-border rounded-lg text-[11px]">
                      {productionStep >= 3 ? (
                        <CheckCircle2 className="w-4 h-4 text-success shrink-0" />
                      ) : productionStep === 2 ? (
                        <RefreshCw className="w-3.5 h-3.5 text-muted-foreground shrink-0 animate-spin" />
                      ) : (
                        <div className="w-3.5 h-3.5 border border-border rounded-full shrink-0" />
                      )}
                      <span className={`${productionStep >= 3 ? 'text-foreground font-semibold' : 'text-muted-foreground'}`}>
                        QC Director: Reading compliance metrics...
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <form onSubmit={handleStartProduction} className="space-y-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Video Topic / Goal</label>
                  <input 
                    required 
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder="e.g. Automating outbound marketing pipelines" 
                    className="w-full px-4 py-2.5 bg-input border border-input-border rounded-xl text-xs focus:ring-1 focus:ring-primary outline-none transition-all"
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Target Audience</label>
                  <input 
                    required 
                    value={audience}
                    onChange={(e) => setAudience(e.target.value)}
                    placeholder="e.g. B2B Sales managers and CEOs" 
                    className="w-full px-4 py-2.5 bg-input border border-input-border rounded-xl text-xs focus:ring-1 focus:ring-primary outline-none transition-all"
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <label className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Tone of Voice</label>
                    <select 
                      value={tone}
                      onChange={(e) => setTone(e.target.value)}
                      className="w-full px-3 py-2.5 bg-input border border-input-border rounded-xl text-xs focus:ring-1 focus:ring-primary outline-none transition-all text-muted-foreground"
                    >
                      <option>Professional & Energetic</option>
                      <option>Casual & Humorous</option>
                      <option>Educational & Analytical</option>
                      <option>Hype & Viral-focused</option>
                    </select>
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Strategy Director</label>
                    <div className="w-full px-3 py-2.5 bg-surface/50 border border-border-subtle rounded-xl text-xs font-semibold text-foreground flex items-center gap-1.5">
                      <div className="w-2 h-2 rounded-full bg-primary animate-pulse" />
                      YoutubeAgent v2.0
                    </div>
                  </div>
                </div>

                <div className="flex justify-end gap-3 pt-5 border-t border-border mt-6">
                  <button 
                    type="button" 
                    onClick={() => setShowProductionModal(false)} 
                    className="px-4 py-2 border border-border text-xs font-semibold rounded-lg hover:bg-surface-hover transition-colors"
                  >
                    Cancel
                  </button>
                  <button 
                    type="submit" 
                    className="px-5 py-2 bg-gradient-to-r from-primary to-accent text-white text-xs font-bold rounded-lg hover:opacity-90 active:scale-95 transition-all"
                  >
                    Launch Director Task
                  </button>
                </div>
              </form>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
