"use client";

import React, { useState } from "react";
import { 
  CheckCircle, 
  XCircle, 
  Edit3, 
  FileText, 
  Share2, 
  Camera, 
  Globe, 
  Search,
  Eye,
  Send,
  MessageSquare,
  Sparkles
} from "lucide-react";

const pendingApprovals = [
  { 
    id: "1", 
    type: "copy", 
    title: "LinkedIn Post: AI in Logistics", 
    agent: "Creative Copy",
    content: {
      linkedin: "The future of logistics is not just automated; it's intelligent. OMNI-SIGMA 360 is leading the charge... #Logistics #AI #SaaS",
      instagram: "Intelligent logistics. Period. 🚀 #AI #OMNISIGMA",
      twitter: "AI is reshaping logistics. Here's how 🧵 1/5..."
    },
    created_at: "1h ago"
  },
  { 
    id: "2", 
    type: "research_report", 
    title: "Market Trend Report: Healthcare Tech", 
    agent: "Trend Scout",
    content: {
      summary: "Healthcare tech is shifting towards patient-centric AI. Key trends include remote monitoring and predictive diagnostics.",
      top_topics: ["Remote Monitoring", "Predictive Diagnostics", "Patient Data Security"]
    },
    created_at: "2h ago"
  },
];

export default function ApprovalCenter() {
  const [selectedId, setSelectedId] = useState<string | null>(pendingApprovals[0].id);

  const selected = pendingApprovals.find(a => a.id === selectedId);

  return (
    <div className="space-y-6 stagger-children">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Quality Control <span className="gradient-text">& Approvals</span></h1>
        <p className="text-sm text-muted-foreground mt-1">Review and approve AI-generated artifacts before they are published.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 h-[calc(100vh-220px)]">
        {/* Sidebar: Pending List */}
        <div className="glass-card flex flex-col overflow-hidden">
          <div className="p-4 border-b border-border flex items-center justify-between">
            <h2 className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Queue ({pendingApprovals.length})</h2>
            <div className="flex gap-1">
              <div className="w-2 h-2 rounded-full bg-warning animate-pulse" />
            </div>
          </div>
          <div className="flex-1 overflow-y-auto divide-y divide-border-subtle">
            {pendingApprovals.map((item) => (
              <button
                key={item.id}
                onClick={() => setSelectedId(item.id)}
                className={`w-full p-4 text-left hover:bg-surface-hover transition-colors flex gap-3 items-start ${selectedId === item.id ? 'bg-primary/5 border-l-2 border-primary' : ''}`}
              >
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${item.type === 'copy' ? 'bg-success/10 text-success' : 'bg-accent/10 text-accent'}`}>
                  {item.type === 'copy' ? <FileText className="w-4 h-4" /> : <Search className="w-4 h-4" />}
                </div>
                <div className="min-w-0">
                  <p className="text-sm font-semibold truncate">{item.title}</p>
                  <div className="flex items-center gap-2 mt-1">
                    <span className="text-[10px] text-muted-foreground">{item.agent}</span>
                    <span className="text-[10px] text-muted-foreground">·</span>
                    <span className="text-[10px] text-muted-foreground">{item.created_at}</span>
                  </div>
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Preview Panel */}
        <div className="lg:col-span-2 glass-card flex flex-col overflow-hidden relative">
          {selected ? (
            <>
              {/* Toolbar */}
              <div className="p-4 border-b border-border flex items-center justify-between bg-surface/30 backdrop-blur-sm sticky top-0 z-10">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center">
                    <Sparkles className="w-4 h-4 text-primary" />
                  </div>
                  <div>
                    <h3 className="text-sm font-bold">{selected.title}</h3>
                    <p className="text-[10px] text-muted-foreground">Generated by {selected.agent}</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <button className="p-2 text-muted-foreground hover:text-foreground hover:bg-muted rounded-lg transition-colors" title="Edit">
                    <Edit3 className="w-4 h-4" />
                  </button>
                  <div className="w-px h-4 bg-border mx-1" />
                  <button className="flex items-center gap-2 px-3 py-1.5 bg-danger/10 text-danger text-xs font-bold rounded-lg hover:bg-danger/20 transition-colors">
                    <XCircle className="w-4 h-4" />
                    Reject
                  </button>
                  <button className="flex items-center gap-2 px-3 py-1.5 bg-success text-white text-xs font-bold rounded-lg hover:bg-success-hover shadow-lg shadow-success/20 transition-all">
                    <CheckCircle className="w-4 h-4" />
                    Approve & Publish
                  </button>
                </div>
              </div>

              {/* Content Area */}
              <div className="flex-1 overflow-y-auto p-6 space-y-6">
                {selected.type === 'copy' && (
                  <div className="grid grid-cols-1 gap-6">
                    {/* LinkedIn Preview */}
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-primary">
                        <Share2 className="w-4 h-4" />
                        <span className="text-xs font-bold uppercase tracking-widest">LinkedIn Draft</span>
                      </div>
                      <div className="p-4 bg-surface/50 border border-border rounded-xl text-sm leading-relaxed whitespace-pre-wrap italic text-foreground/90">
                        "{selected.content.linkedin}"
                      </div>
                    </div>

                    {/* Instagram Preview */}
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-accent">
                        <Camera className="w-4 h-4" />
                        <span className="text-xs font-bold uppercase tracking-widest">Instagram Caption</span>
                      </div>
                      <div className="p-4 bg-surface/50 border border-border rounded-xl text-sm leading-relaxed italic text-foreground/90">
                        "{selected.content.instagram}"
                      </div>
                    </div>

                    {/* Twitter Preview */}
                    <div className="space-y-2">
                      <div className="flex items-center gap-2 text-info">
                        <Globe className="w-4 h-4" />
                        <span className="text-xs font-bold uppercase tracking-widest">Twitter Thread</span>
                      </div>
                      <div className="p-4 bg-surface/50 border border-border rounded-xl text-sm leading-relaxed italic text-foreground/90">
                        "{selected.content.twitter}"
                      </div>
                    </div>
                  </div>
                )}

                {selected.type === 'research_report' && (
                  <div className="space-y-4">
                    <div className="flex items-center gap-2 text-accent">
                      <Search className="w-4 h-4" />
                      <span className="text-xs font-bold uppercase tracking-widest">Intelligence Report</span>
                    </div>
                    <div className="p-6 bg-surface/50 border border-border rounded-xl space-y-4">
                      <div>
                        <h4 className="text-sm font-bold mb-2">Executive Summary</h4>
                        <p className="text-sm text-muted-foreground leading-relaxed">{selected.content.summary}</p>
                      </div>
                      <div>
                        <h4 className="text-sm font-bold mb-2">Key Trends Detected</h4>
                        <div className="flex flex-wrap gap-2">
                          {selected.content.top_topics.map((topic: string, i: number) => (
                            <span key={i} className="px-3 py-1 rounded-full bg-primary/10 text-primary text-[11px] font-semibold border border-primary/20">
                              {topic}
                            </span>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-muted-foreground p-12 text-center">
              <div className="w-16 h-16 rounded-full bg-muted/30 flex items-center justify-center mb-4">
                <CheckCircle className="w-8 h-8 opacity-20" />
              </div>
              <p className="text-sm font-medium">Select an item from the queue to review</p>
              <p className="text-xs mt-1">All clear! No items currently awaiting approval.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
